# Generated by Django 4.0.2 on 2022-02-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_comment_book_alter_comment_owner_of_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner_of_comment',
            field=models.CharField(max_length=255),
        ),
    ]
